import { onAuthStateChanged } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-auth.js";
import { collection, doc, getDocs, serverTimestamp, writeBatch } from "https://www.gstatic.com/firebasejs/12.16.0/firebase-firestore.js";
import { auth, db } from "./firebase-client.js?v=5";

const ADMIN_EMAIL="sudarshandesai74@gmail.com",$=selector=>document.querySelector(selector);
const seasonSelect=$("#rosterAdminSeason"),teamsPanel=$("#rosterAdminTeams"),message=$("#rosterAdminMessage"),dialog=$("#rosterReplacementDialog"),form=$("#rosterReplacementForm"),playerSelect=$("#replacementPlayerId");
let players=[],assignmentsById=new Map(),teamsById=new Map();
const esc=value=>String(value??"").replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[char]);
const isAdmin=()=>Boolean(auth.currentUser?.emailVerified&&auth.currentUser.email?.toLowerCase()===ADMIN_EMAIL);
const openDialog=()=>typeof dialog.showModal==="function"?dialog.showModal():dialog.setAttribute("open","");
const closeDialog=()=>dialog.open?(typeof dialog.close==="function"?dialog.close():dialog.removeAttribute("open")):null;
const playerName=item=>item.displayName||item.fullName||`${item.firstName||""} ${item.lastName||""}`.trim()||item.playerId;

async function loadSeasons(){if(!isAdmin())return;const snapshot=await getDocs(collection(db,"seasons")),seasons=snapshot.docs.map(item=>({seasonId:item.id,...item.data()})).sort((a,b)=>Number(b.year||0)-Number(a.year||0)||String(b.term||"").localeCompare(String(a.term||"")));seasonSelect.innerHTML=seasons.map(item=>`<option value="${esc(item.seasonId)}">${esc(item.name||item.seasonId)}</option>`).join("");if(seasons.some(item=>item.seasonId==="AO-S-2026"))seasonSelect.value="AO-S-2026";await loadRoster();}
async function loadPlayers(){if(players.length)return;const snapshot=await getDocs(collection(db,"playerPrivate"));players=snapshot.docs.map(item=>({playerId:item.id,...item.data()})).filter(item=>item.status!=="inactive").sort((a,b)=>playerName(a).localeCompare(playerName(b)));playerSelect.innerHTML='<option value="">Select a Firebase player</option>'+players.map(item=>`<option value="${esc(item.playerId)}">${esc(playerName(item))} · ${esc(item.playerId)}</option>`).join("");}
async function loadRoster(){if(!isAdmin()||!seasonSelect.value)return;teamsPanel.innerHTML='<p class="muted">Loading Firebase team rosters...</p>';message.textContent="Reading operational roster assignments.";try{await loadPlayers();const seasonId=seasonSelect.value,[teamSnapshot,assignmentSnapshot]=await Promise.all([getDocs(collection(db,"seasons",seasonId,"teams")),getDocs(collection(db,"seasons",seasonId,"rosterAssignments"))]);teamsById=new Map(teamSnapshot.docs.map(item=>[item.id,{teamId:item.id,...item.data()}]));const assignments=assignmentSnapshot.docs.map(item=>({assignmentId:item.id,...item.data()})).filter(item=>item.status==="active");assignmentsById=new Map(assignments.map(item=>[item.assignmentId,item]));const byTeam=new Map();assignments.forEach(item=>{const list=byTeam.get(item.teamId)||[];list.push(item);byTeam.set(item.teamId,list);});teamsPanel.innerHTML=[...teamsById.values()].sort((a,b)=>String(a.name).localeCompare(String(b.name))).map((team,index)=>{const rows=(byTeam.get(team.teamId)||[]).sort((a,b)=>Number(a.rankNumber)-Number(b.rankNumber)).map(item=>{const replaced=item.assignmentType==="replacement"&&item.originalPlayerNameSnapshot;return `<div class="roster-admin-row"><span>R${Number(item.rankNumber)}</span><div><b>${esc(item.playerNameSnapshot||item.playerId)}</b>${replaced?`<small>${esc(item.originalPlayerNameSnapshot)} → ${esc(item.playerNameSnapshot)}</small>`:"<small>Original assignment</small>"}</div><span class="badge ${replaced?"orange":"gray"}">${replaced?"Replacement":"Original"}</span><button type="button" class="secondary compact-button" data-replace-assignment="${esc(item.assignmentId)}">Replace player</button></div>`;}).join("");return `<details class="roster-admin-team" ${index===0?"open":""}><summary><div><b>${esc(team.name||team.teamId)}</b><small>Captain · ${esc(team.captainNameSnapshot||"Not recorded")}</small></div><span class="badge navy">${(byTeam.get(team.teamId)||[]).length} ranks</span></summary><div>${rows||'<div class="empty-state compact">No active roster assignments</div>'}</div></details>`;}).join("")||'<div class="empty-state compact"><b>No teams found</b></div>';teamsPanel.querySelectorAll("[data-replace-assignment]").forEach(button=>button.addEventListener("click",()=>startReplacement(button.dataset.replaceAssignment)));message.textContent=`${teamsById.size} teams and ${assignments.length} active ranks loaded from Firebase.`;}catch(error){console.error("Roster admin load failed",error);teamsPanel.innerHTML=`<div class="empty-state compact"><b>Roster could not be loaded</b><p>${esc(error.message||"Refresh and try again.")}</p></div>`;message.textContent="Firebase roster access failed.";}}
function startReplacement(assignmentId){const assignment=assignmentsById.get(assignmentId),team=teamsById.get(assignment?.teamId);if(!assignment)return;$("#replacementAssignmentId").value=assignmentId;$("#rosterReplacementContext").textContent=`${team?.name||assignment.teamId} · Rank ${assignment.rankNumber} · Current: ${assignment.playerNameSnapshot||assignment.playerId}`;playerSelect.value="";$("#rosterReplacementMessage").textContent="The original player remains visible in roster history.";openDialog();}
form?.addEventListener("submit",async event=>{event.preventDefault();if(!isAdmin())return;const seasonId=seasonSelect.value,assignment=assignmentsById.get($("#replacementAssignmentId").value),replacement=players.find(item=>item.playerId===playerSelect.value);if(!assignment||!replacement)return;const replacementName=playerName(replacement);if(replacement.playerId===assignment.playerId){$("#rosterReplacementMessage").textContent="Choose a different player.";return;}const save=$("#saveRosterReplacement");save.disabled=true;$("#rosterReplacementMessage").textContent="Saving replacement to Firebase...";try{const batch=writeBatch(db),historyId=`${assignment.assignmentId}-H-${Date.now()}`,originalPlayerId=assignment.originalPlayerId||assignment.playerId,originalPlayerNameSnapshot=assignment.originalPlayerNameSnapshot||assignment.playerNameSnapshot,activeUpdate={playerId:replacement.playerId,playerNameSnapshot:replacementName,assignmentType:"replacement",status:"active",originalPlayerId,originalPlayerNameSnapshot,replacedPlayerId:assignment.playerId,replacedPlayerNameSnapshot:assignment.playerNameSnapshot,replacedAt:serverTimestamp(),replacedByUid:auth.currentUser.uid},history={seasonId,teamId:assignment.teamId,rankNumber:Number(assignment.rankNumber),playerId:assignment.playerId,playerNameSnapshot:assignment.playerNameSnapshot,assignmentType:assignment.assignmentType||"original",status:"replaced",replacementPlayerId:replacement.playerId,replacementPlayerNameSnapshot:replacementName,replacedAt:serverTimestamp(),replacedByUid:auth.currentUser.uid};batch.set(doc(db,"seasons",seasonId,"rosterAssignments",assignment.assignmentId),activeUpdate,{merge:true});batch.set(doc(db,"seasons",seasonId,"rosterAssignments",historyId),history);await batch.commit();closeDialog();message.textContent=`Rank ${assignment.rankNumber} updated to ${replacementName}.`;await loadRoster();}catch(error){console.error("Roster replacement failed",error);$("#rosterReplacementMessage").textContent=error.message||"Replacement could not be saved.";}finally{save.disabled=false;}});
seasonSelect?.addEventListener("change",loadRoster);$("#refreshRosterAdmin")?.addEventListener("click",loadRoster);$("#closeRosterReplacement")?.addEventListener("click",closeDialog);$("#cancelRosterReplacement")?.addEventListener("click",closeDialog);onAuthStateChanged(auth,user=>{if(user?.emailVerified&&user.email?.toLowerCase()===ADMIN_EMAIL)loadSeasons();});
